version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    env_file:
      - .env.docker
    networks:
      - finservice_network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: jwtproject
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - finservice_network

networks:
  finservice_network:
    driver: bridge